name: publish

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          tags: ja1den/portfolio
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_secret: ${{ secrets.HOOK_SECRET }}
          webhook_url: ${{ secrets.HOOK_URL }}
